name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca8146e07231dcfd4fb90ea03ea0c95b1b48fe3f2e4fb810cb22e8b7cf7ab01a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.43"
