name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3db953f485b9536d0fe203a9fe66711bdfbe7ff6e2698e559165cab81b752fd9"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.2"
