name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810728c2a50ed2bf8a18d97add1310b70ae79b5918c7671264f59f2a82c674e2"

[versions]
minecraft = "1.19.3"
quilt = "0.18.8"
