name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dabc6b1c9127658727a669fa93ec567a1dffad3b07746c8a0fc48ede2c294186"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
