name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41ec86b6f2d369e4c247cb97f446a5caf02f13a56964cb4db2a674933e31fbae"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.3"
