name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bfcedbf60a4b27b5cf5e9b80f1459635eb4896818af254c52fa9f62765aa822"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
