name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0329249e993ee619710192fbfc3831c8a53a7cd41b44d3c5cf766e01975df100"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
