name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "453163ed9526f8d355082a216fa0d31822782a476746ec7c8f65ae0cd450bb9b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.79"
