name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "333bdfb438be5b93fa79227d6d869434406cbc7c3373bf0effdcbdc817edeb7e"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.43"
