name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0470813eb60ac630cb3c1858134574052978e3cc430a31b70e5c1e7d2890998c"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
