name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20a0468a82ce92c47bd3b857c55e961f997bc7e7993e57e7627ec82b63ea560b"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
