name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "318ad3d7945057f107b0251ae609b1a43cc9442cffef0d7f53736bd11582e6cd"

[versions]
minecraft = "1.19.4"
quilt = "0.18.5"
