name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6c50f37e151bef19a722c85971f74ed2fc21f117482e592f2ca230b26cd3685"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
