name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d21734db4a083b4bfd1ae26b89e717eb53158be2c7a8f7ada77ae33f8a2c2af6"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
