name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79444249c0124e5867b29fb9c143470a0adb6bd05e207330681cf22c2821389c"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
