name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a9bf6936696dac814474cb80df37aedb9c6a3c94a8f24e3b3e71ed8c5dbad85"

[versions]
minecraft = "1.19.4"
quilt = "0.18.6"
