name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b86d93750b7fb7202b02f62268803a9c63b62b600f4e5acd3a1df717303502"

[versions]
minecraft = "1.19.4"
quilt = "0.18.5"
