name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "301ffa4cd22d47799b9441dbf8f7c0ff508b4ba34f9cbdb2d83db0b40979dca6"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
