name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4de7e8617813409ef78a82653ed6c4e9623859ae14bbfebe0b17c9bb7584b88a"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.2"
