name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "147813a2bea6ec04e9ab7962a1e0c32c532a3401b90276b3050a437f009b19cb"

[versions]
minecraft = "1.19.4"
quilt = "0.18.5"
