name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "352f46dddd6b2b77c73d8353c953ffc81abcc3dd03ddde2474ce32232d6d86e4"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
