name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f0cc3e29c1d8838e04ec71d07a0ef15a8651f0b59165987c7e38dcede08fb17"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
