name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a890cc97a7a9939f534381cb5852ed8d4b7b51a161be162ccd154d288be85782"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
