name = "Nova Companion"
author = "Nova Network Team"
version = "3.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c37d854ed5195aef67e0adb67004a367495363fd362383ea025d3477fffb97e"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
