name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "461416af6e8bb9644983b55ddfd541fca3410e99a7fd66d1545a917bad414e03"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
