name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "797359ee4d1dd59ae1fd73f4dd131b9127614a4dc6d2b57c624de588edb57464"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
