name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82a8c6e4a02eaba7fa95de2039c5ff13c1000ed7696646a26b2cef62c767f5e7"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
