name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f047d095024de96eb350f58aac4d19f536ccd33b766d8631019146739e35f7"

[versions]
minecraft = "1.19.3"
quilt = "0.18.8"
