name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e446983ca18bb1d097eab45f7515b1f8ec26b3512defebd368cc08a29a790456"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
