name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d3168ac864cdb73afc5083703b9ef3b586b703a5878205b85e851e9f7cb211b"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
