name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "971e4ad5ec80b20c41a52938d6844a3bf42ab3dd79fc4656e4ff157008c9b6fe"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
