name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f7be26b9c0a9fa014d522fef1f194b1e5de35d37a2c9500a5b2b93e1506ef25"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
