name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "209cc69fb425b0322425cf09b9f3f3d53f69e050bfca8699486bf41d3016dacc"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.2"
