name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9191411d21673df186882a7306085ee18f931728f92c35b7aafa160f81730eba"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
