name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6161021a3014898adf5723b8e15565604e79a61c9339a8f716af38ecf732cef2"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
