name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98790611b3b90d67389ced7feed2eb8cc3e702c83cb2630d07919a9ea2d346a4"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
