name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a758568b656df39f7898eea9dfa00c9a7b20ff056c70457e88464dd01d539b71"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
