name = "Nova Companion"
author = "Nova Network Team"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "129820cd1bf52c1e26b5832977633f8be73031d153b45b3b590c5f9e6f36e751"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
