debug = false

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[activations.46927964-3207-377a-84d7-26a82d52be1e]
toggle = false
type = "INHERIT"
[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 78
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.whisper.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 342
type = "KEYSYM"



[voice]
disabled = false
microphone_disabled = false
activation_threshold = -40.0
input_device = ""
output_device = ""
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = true
stereo_capture = false

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
whisper = "OFF"
groups = "ALWAYS"
